[build]
  functions = "functions"
  
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "
      default-src 'self';
      script-src 'self' 'unsafe-eval' https://pyscript.net https://cdn.jsdelivr.net;
      style-src 'self' https://pyscript.net https://cdn.jsdelivr.net;
      img-src 'self' data:;
      connect-src 'self' https://api.openai.com https://cdn.jsdelivr.net;
      font-src 'self' https://pyscript.net;
    "
